Cleaning, added delete function, better filtering and space removal.

diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -1,19 +1,20 @@
 #!/usr/bin/env bash
+
 [ -z "$DEBUG" ] && DEBUG="0"
 
 debug() {
-    [ "$DEBUG" -eq "1" ] && return 0
-    return 1
+	[ "$DEBUG" -eq "1" ] && return 0
+	return 1
 }
 
 d() {
-    debug && echo "debug: $*" >&2
+	debug && echo "debug: $*" >&2
 }
 
 e() {
-    echo "error: $*" >&2
+	echo "error: $*" >&2
 }
 
 w() {
-    e "warn: $*" >&2
+	e "warn: $*" >&2
 }
diff --git a/edit b/edit
--- a/edit
+++ b/edit
@@ -1,19 +1,30 @@
 #!/usr/bin/env bash
+
 source functions
 if ! profile_exists "$1"; then
-    echo "Profile '$1' could not be loaded" >&2
-    echo "Available profiles: $(list_profiles)"
-    exit 1
+	echo "Profile '$1' could not be loaded" >&2
+	echo "Available profiles: $(list_profiles)"
+	exit 1
 fi
 
 if [ -z "$2" ]; then
-    if [ -z "$EDITOR" ]; then
-        e="vim"
-    else
-        e=$EDITOR
-    fi
+	if [ -z "$EDITOR" ]; then
+
+		if which nano; then
+			e="nano"
+		elif which pico; then
+			e="pico"
+		elif which vim; then
+			e="vim"
+		else
+			e="vi"
+		fi
+
+	else
+		e=$EDITOR
+	fi
 else
-    e=$2
+	e=$2
 fi
 
 "$e" "$(profile_dir)/$1"
diff --git a/load b/load
--- a/load
+++ b/load
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
+
 source functions
 if profile=$(load_profile "$1");then
-    apply_settings "$profile"
+
+	profile=$(remove_spaces "$profile")
+
+	apply_settings "$profile"
 else
-    echo "Failed to load profile ($?)"
-    exit 1
+	echo "Failed to load profile ($?)"
+	exit 1
 fi
diff --git a/view b/view
--- a/view
+++ b/view
@@ -1,18 +1,18 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
+
 source functions
-source debug
 
 d "View starting"
 if [ -z "$1" ]; then
-    d "Viewing current values"
-    profile=$(current_profile)
+	d "Viewing current values"
+	profile=$(current_profile)
 else
-    if profile=$(load_profile "$1");then
-        d "Loading profile '$1'"
-    else
-        echo "Failed to load profile ($?)" >&2
-        exit 1
-    fi
+	if profile=$(load_profile "$1");then
+		d "Loading profile '$1'"
+	else
+		echo "Failed to load profile ($?)" >&2
+		exit 1
+	fi
 fi
 
-echo $profile | sed -e 's/ /\n/g' -e 's/=/ ... /g'
+echo "$profile" | sed -e 's/ /\n/g' -e 's/=/ .... /g'
