tabs to spaces

diff --git a/delete b/delete
--- a/delete
+++ b/delete
@@ -3,11 +3,11 @@
 source functions
 if profile_exists "$1"; then
 
-	f="$(profile_dir)""$1"
-	rm $f
-	echo "Profile deleted."
+    f="$(profile_dir)""$1"
+    rm $f
+    echo "Profile deleted."
 
 else
-	echo "Profile not found ($?)"
-	exit 1
+    echo "Profile not found ($?)"
+    exit 1
 fi
diff --git a/edit b/edit
--- a/edit
+++ b/edit
@@ -2,29 +2,29 @@
 
 source functions
 if ! profile_exists "$1"; then
-	echo "Profile '$1' could not be loaded" >&2
-	echo "Available profiles: $(list_profiles)"
-	exit 1
+    echo "Profile '$1' could not be loaded" >&2
+    echo "Available profiles: $(list_profiles)"
+    exit 1
 fi
 
 if [ -z "$2" ]; then
-	if [ -z "$EDITOR" ]; then
+    if [ -z "$EDITOR" ]; then
 
-		if which nano; then
-			e="nano"
-		elif which pico; then
-			e="pico"
-		elif which vim; then
-			e="vim"
-		else
-			e="vi"
-		fi
+        if which nano; then
+        	e="nano"
+        elif which pico; then
+        	e="pico"
+        elif which vim; then
+        	e="vim"
+        else
+        	e="vi"
+        fi
 
-	else
-		e=$EDITOR
-	fi
+    else
+        e=$EDITOR
+    fi
 else
-	e=$2
+    e=$2
 fi
 
 "$e" "$(profile_dir)/$1"
diff --git a/load b/load
--- a/load
+++ b/load
@@ -3,10 +3,10 @@
 source functions
 if profile=$(load_profile "$1");then
 
-	profile=$(remove_spaces "$profile")
+    profile=$(remove_spaces "$profile")
 
-	apply_settings "$profile"
+    apply_settings "$profile"
 else
-	echo "Failed to load profile ($?)"
-	exit 1
+    echo "Failed to load profile ($?)"
+    exit 1
 fi
