Near first usable release.

diff --git a/view b/view
--- a/view
+++ b/view
@@ -3,9 +3,15 @@ source functions
 source debug
 
 d "View starting"
-if profile=$(load_profile "$1");then
-    echo $profile | sort | perl -p -e 's/=/ -> /g'
+if [ -z "$1" ]; then
+    d "Viewing current values"
+    profile=$(current_profile)
 else
-    echo "Failed to load profile ($?)" >&2
-    exit 1
+    if profile=$(load_profile "$1");then
+        d "Loading profile '$1'"
+    else
+        echo "Failed to load profile ($?)" >&2
+        exit 1
+    fi
 fi
+echo $profile | perl -p -e 's/ /\n/g' | perl -p -e 's/=/ -> /g'
